[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.environment]
NODE_ENV = "production"
PORT = "10000"

# Configuração específica para o backend
[build.environment]
NODE_ENV = "production"

# Especificar que queremos apenas o backend
[build.scripts]
build = "cd backend && npm install"
start = "cd backend && npm start"
