[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Configuração específica para o backend
[build.environment]
NODE_ENV = "production"
