[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm install && npm start"
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[build.environment]
NODE_ENV = "production"
